---
title: "Edificios"
author: "Andrés Camero"
output: pdf_document
---

```{r setup, echo=FALSE, warning=FALSE, message=FALSE}
rm(list = ls())
options(error=traceback)
library(clValid)
library(NbClust)
library(RMySQL)
library(fpc)
library(knitr)

set.seed(3)
```

``` {r echo=FALSE, warning=FALSE}
setwd("/home/andu/Documentos/uma/PHD/vatia/data/proc")
raw_data <- read.table("data.txt",sep="\t")
raw_meta <- read.table("meta.txt", sep="\t", encoding = "latin1")
```

Se han cargado `r nrow(raw_meta)` edificios.

``` {r echo=FALSE, warning=FALSE}
divisions <- as.data.frame(matrix( c(1,"Agriculture, Forestry and Fishing", 2,"Mining", 3,"Construction", 4,"Manufacturing", 5,"Transportation, Communications, Electric, Gas and Sanitary service", 6, "Wholesale Trade", 16,"Retail Trade", 7,"Finance, Insurance and Real Estate", 8,"Services", 9,"Public Administration", 10, "Nonclassifiable"), ncol=2, byrow=TRUE))
colnames(divisions) <- c("key","desc")

raw_meta$division <- c(4, 9, 9, 8, 6, 1, 1, 3, 8, 8
,4, 9, 9, 6, 4, 8, 8, 8, 8, 8
,9, 8, 8, 4, 8, 8, 8, 8, 8, 8
,8, 8, 8, 8, 8, 8, 8, 8, 8, 8
,4, 8, 8, 8, 3, 9, 1, 1, 8, 9
,8, 8, 8, 4, 4, 8, 9, 8, 8, 8
,8, 9, 8, 6)

table(raw_meta$division)

categories <- as.data.frame( matrix( c(70, "Hotels, Rooming Houses, Camps, and Other Lodging Services"
,73, "Business Services"
,79, "Amusement and Recreation Services"
,80, "Health Services"
,82, "Educational Services"
,84, "Museums, Art Galleries, and Botanical and Zoological Gardens"
,86, "Membership Organizations"
,87, "Engineering, Accounting, Research, Management, and Related Services"
,89, "Miscellaneous Services"), ncol=2, byrow=TRUE) )
colnames(categories) <- c("key", "desc")

raw_meta$category <- 0
raw_meta$category[raw_meta$division==8] <- c(82, 84, 87, 80, 70, 87, 87, 79, 80, 82, 
86, 86, 87, 87, 80, 80, 87, 89, 89, 80, 
89, 89, 89, 89, 73, 89, 84, 84, 86, 79, 
89, 73, 80, 80, 80, 80, 80, 82, 80)

table(raw_meta$category)

```


``` {r echo=FALSE, warning=FALSE}
divs <- raw_meta$division
descs <- rbind(divisions, categories)
divs <- as.data.frame(divs)
divs$order <- 1:nrow(divs)
divs_descs <- merge(divs, descs, by.x="divs", by.y="key", sort=TRUE)
divs_descs[order(divs_descs$order),]

cats <- raw_meta$category
cats <- as.data.frame(cats)
cats$order <- 1:nrow(cats)
cats_descs <- merge(cats, descs, by.x="cats", by.y="key", sort=TRUE, all.x=TRUE)
#cats_descs[order(cats_descs$order),]

mins <- list()
maxs <- list()
means <- list()
agg_means <- list()

for(i in 1:nrow(raw_meta)) {
  mins[i] <- min( raw_data[which(raw_data$file_name == raw_meta$file_name[i]),3:98] )
  maxs[i] <- max( raw_data[which(raw_data$file_name == raw_meta$file_name[i]),3:98] )
  means[i] <- mean( unlist(raw_data[which(raw_data$file_name == raw_meta$file_name[i]),3:98] ))
  agg_means[i] <- mean(rowSums(raw_data[which(raw_data$file_name == raw_meta$file_name[i]),3:98]))
}

sum_stats <- data.frame( unlist(divs_descs[order(divs_descs$order),"desc"]), unlist(cats_descs[order(cats_descs$order),"desc"]), unlist(mins), unlist(maxs), unlist(means), unlist(agg_means) )
colnames(sum_stats) <- c("division", "category", "min", "max", "mean", "agg_mean")

write.csv(sum_stats, file="sum_stats.csv")

```